declare const cheerpjInit: (options?: object) => Promise<void>;
declare const cheerpjRunMain: any;
declare const cheerpjRunJar: any;
declare const cheerpjRunLibrary: any;
declare const cheerpjCreateDisplay: any;
declare const cjFileBlob: any;
declare const cjGetRuntimeResources: any;
declare const cjGetProguardConfiguration: any;
declare const dumpMethod: any;
declare const dumpClass: any;
declare const dumpAllThreads: any;
declare const cheerpjAddStringFile: any;
